/**
 * Build-time insights fetch.
 *
 * Reads the public Axleta Blogger feed and writes a typed module consumed by
 * the site. Only metadata is taken — title, date, category, link and a plain
 * text excerpt. Post bodies are not scraped or reproduced.
 *
 * The blog feed sends no Access-Control-Allow-Origin header, so this cannot be
 * fetched from the browser; doing it at build time is the only robust option.
 * If the request fails the previous generated module is left untouched, so a
 * build never breaks because the blog is down.
 *
 *   node --experimental-strip-types scripts/fetch-insights.ts
 */

import { writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const FEED_URL =
  'https://blog.axleta.com/feeds/posts/default?alt=json&max-results=12';
const OUT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../src/data/insights.generated.ts',
);

type FeedLink = { rel?: string; type?: string; href?: string };
type FeedEntry = {
  title?: { $t?: string };
  link?: FeedLink[];
  published?: { $t?: string };
  updated?: { $t?: string };
  category?: { term?: string }[];
  summary?: { $t?: string };
  content?: { $t?: string };
};

/** Blogger's blog-level category, which appears first on every entry. */
const BLOG_CATEGORY = 'Axleta';

type Feed = { feed?: { entry?: FeedEntry[] } };

const HTML_ENTITIES: Record<string, string> = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&nbsp;': ' ',
};

function decodeEntities(input: string): string {
  return input
    .replace(/&(?:amp|lt|gt|quot|#39|nbsp);/g, (m) => HTML_ENTITIES[m] ?? m)
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCharCode(Number(code)));
}

function toPlainText(html: string): string {
  return decodeEntities(
    html
      .replace(/<script[\s\S]*?<\/script>/gi, ' ')
      .replace(/<style[\s\S]*?<\/style>/gi, ' ')
      .replace(/<[^>]+>/g, ' '),
  )
    .replace(/\s+/g, ' ')
    .trim();
}

function excerpt(text: string, max = 220): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > 0 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\u2014-]$/, '')}\u2026`;
}

async function main(): Promise<void> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10_000);

  let payload: Feed;
  try {
    const res = await fetch(FEED_URL, {
      signal: controller.signal,
      headers: { accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`feed responded ${res.status}`);
    payload = (await res.json()) as Feed;
  } catch (error) {
    console.warn(
      `[insights] feed unavailable (${(error as Error).message}). Keeping the committed snapshot.`,
    );
    return;
  } finally {
    clearTimeout(timeout);
  }

  const entries = (payload.feed?.entry ?? [])
    .map((entry) => {
      const html = entry.summary?.$t ?? entry.content?.$t ?? '';
      // rel=alternate + text/html is the canonical post page. The other links
      // point at the comments feed and the Blogger edit endpoint.
      const link = entry.link?.find(
        (l) => l.rel === 'alternate' && l.type === 'text/html',
      )?.href;
      const date = entry.published?.$t ?? entry.updated?.$t ?? '';
      if (!link || !date) return null;

      // Blogger puts the blog-level label first, then the post's own labels.
      const labels = (entry.category ?? [])
        .map((c) => c.term)
        .filter((t): t is string => Boolean(t) && t !== BLOG_CATEGORY);
      const category = labels[0] ?? BLOG_CATEGORY;

      return {
        title: decodeEntities(entry.title?.$t ?? 'Untitled').trim(),
        href: link,
        date,
        category,
        excerpt: excerpt(toPlainText(html)),
      };
    })
    .filter((e): e is NonNullable<typeof e> => e !== null);

  if (entries.length === 0) {
    console.warn('[insights] feed returned no usable entries. Keeping the committed snapshot.');
    return;
  }

  const body = entries
    .map(
      (e) =>
        `  {\n` +
        `    title: ${JSON.stringify(e.title)},\n` +
        `    href: ${JSON.stringify(e.href)},\n` +
        `    date: ${JSON.stringify(e.date)},\n` +
        `    category: ${JSON.stringify(e.category)},\n` +
        `    excerpt: ${JSON.stringify(e.excerpt)},\n` +
        `  },`,
    )
    .join('\n');

  const file =
    `/* AUTO-GENERATED by scripts/fetch-insights.ts. Do not edit by hand. */\n` +
    `/* Source: ${FEED_URL} */\n\n` +
    `export type Insight = {\n` +
    `  title: string;\n` +
    `  href: string;\n` +
    `  date: string;\n` +
    `  category: string;\n` +
    `  excerpt: string;\n` +
    `};\n\n` +
    `export const insights: Insight[] = [\n${body}\n];\n`;

  await writeFile(OUT, file, 'utf8');
  console.log(`[insights] wrote ${entries.length} entries to src/data/insights.generated.ts`);
}

main().catch(async (error: unknown) => {
  console.warn(`[insights] ${(error as Error).message}`);
  try {
    await readFile(OUT, 'utf8');
  } catch {
    console.warn('[insights] no committed snapshot available — run npm run data:insights');
  }
});
