/* AUTO-GENERATED by scripts/fetch-insights.ts. Do not edit by hand. */
/* Source: https://blog.axleta.com/feeds/posts/default?alt=json&max-results=12 */

export type Insight = {
  title: string;
  href: string;
  date: string;
  category: string;
  excerpt: string;
};

export const insights: Insight[] = [
  {
    title: "Building Blocks for Scalable Business Success via ERP system",
    href: "https://blog.axleta.com/2026/08/building-blocks-for-scalable-business.html",
    date: "2026-08-27T22:55:10.976-06:00",
    category: "ERP",
    excerpt: "If you have ever been part of an Enterprise Resource Planning (ERP) rollout, you know it is far more than just \"installing new software.\" It is an architectural overhaul of how your entire business operates. When…",
  },
  {
    title: "Why subdomains are used for mails ?",
    href: "https://blog.axleta.com/2026/05/why-subdomains-are-used-for-mails.html",
    date: "2026-05-11T23:27:00.004-06:00",
    category: "Google Workspace",
    excerpt: "Here at Axleta, we are also using the \"@mail.axleta.com\" for emails. We would like to introduce the benefits of using a subdomain. Separation of services : mail.axleta.com is distinct from www.axleta.com . This…",
  },
  {
    title: "Boost your PC with Free Microsoft Tool - Microsoft PC Manager",
    href: "https://blog.axleta.com/2026/05/boost-your-pc-with-free-microsoft-tool.html",
    date: "2026-05-03T00:35:00.003-06:00",
    category: "IT",
    excerpt: "Boost your PC’s speed and reclaim your productivity! As IT professionals, we often ask how to fix a lagging computer without installing \"bloatware and malware\". Our top recommendation is the Microsoft PC Manager…",
  },
  {
    title: "How to clearly identify the \"Cancellation\" document in SAP Business One",
    href: "https://blog.axleta.com/2022/02/how-to-clearly-identify-cancellation.html",
    date: "2022-02-11T11:44:00.004-06:00",
    category: "ERP",
    excerpt: "How to clearly identify the \"Cancellation\" document in SAP Business One When raising a cancellation document against an AR or AP document, it shows the status as closed with \"Cancellation\" in the new cancellation…",
  },
  {
    title: "How to overcome the Adobe Flash Player Problem?",
    href: "https://blog.axleta.com/2021/05/how-to-overcome-adobe-flash-player.html",
    date: "2021-05-11T12:10:00.001-06:00",
    category: "ERP",
    excerpt: "When you have to deal with .swf files for referring to SAP Business One ERP Training Videos and Dashboard Solution, you might have problems like not opening the.swf files with the existing flash player because it is no…",
  },
  {
    title: "How to edit the office file without changing the file format  from Gmail and Google Drive",
    href: "https://blog.axleta.com/2021/02/how-to-edit-office-file-without.html",
    date: "2021-02-10T22:39:00.001-06:00",
    category: "Axleta",
    excerpt: "When we work with cross platforms like Microsoft and Google, it is quite helpful to create, change and update files in a single format without changing the another file format. For example, we received a mail with a…",
  },
  {
    title: "Easiest way to reduce your company's operating expenses",
    href: "https://blog.axleta.com/2021/02/easiest-way-to-reduce-your-companys.html",
    date: "2021-02-08T12:10:00.000-06:00",
    category: "Axleta",
    excerpt: "When we are operating a business in the field, cost drives a major role especially for operating the business such as often abbreviated as OPEX, that includes rent, equipment purchases, inventory purchases, marketing…",
  },
  {
    title: "Be in fear of ERP ?",
    href: "https://blog.axleta.com/2021/01/be-in-fear-of-erp.html",
    date: "2021-01-28T00:56:00.002-06:00",
    category: "ERP",
    excerpt: "Especially, small and medium-sized enterprises (SMEs) have fear when talking about an ERP system. Actually, what is the fear and fear factor?. It is quite important to discuss these sections because most organizations…",
  },
  {
    title: "What are the advantages of having an ERP system?",
    href: "https://blog.axleta.com/2021/01/what-are-advantages-of-having-erp-system.html",
    date: "2021-01-24T08:44:00.001-06:00",
    category: "ERP",
    excerpt: "It is a real question today because most the organization are using ERP systems to cater daily business operations and some of the organizations are looking a new system to effectively run the business operation. Both…",
  },
  {
    title: "Why do you need a server in your organization",
    href: "https://blog.axleta.com/2021/01/why-do-you-need-server-in-your.html",
    date: "2021-01-17T13:33:00.001-06:00",
    category: "IT",
    excerpt: "There are different types of businesses and organizations in the world that can be varied according to the business functions and their capacity. When considering the small and mediums sized enterprises whose business…",
  },
  {
    title: "Starting with an 8GB Dedicated Server and reliably host your applications and files",
    href: "https://blog.axleta.com/2021/01/starting-with-8-gb-dedicated-server-and.html",
    date: "2021-01-13T12:28:00.003-06:00",
    category: "IT",
    excerpt: "Today most organizations are looking at the managed services because they have concerns like this. During this unprecedented time, how remotely access business applications and files? How to remotely access the servers…",
  },
  {
    title: "Hard and Soft allocation of stock in SAP Business One",
    href: "https://blog.axleta.com/2020/12/hard-and-soft-allocation-of-stock-in.html",
    date: "2020-12-05T01:26:00.001-06:00",
    category: "ERP",
    excerpt: "When you require to allocate the stock in a particular item in the inventory, you must have a solution to do that. In different instances, companies need to allocate quantities for different requirements. In retail…",
  },
];
